name: CI

on:
  push:
    branches: [main]
    tags:
      - '*'
  pull_request:
    branches: [main]

jobs:
  ci:
    name: CI
    runs-on: blacksmith-4vcpu-ubuntu-2204
    timeout-minutes: 10
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Setup Node.js 20
        uses: useblacksmith/setup-node@v5
        with:
          node-version: 20
          registry-url: 'https://registry.npmjs.org'

      - name: Cache dependencies
        id: cache
        uses: useblacksmith/cache@v5
        with:
          path: ./node_modules
          key: modules-${{ hashFiles('package-lock.json') }}

      - name: Install dependencies
        if: steps.cache.outputs.cache-hit != 'true'
        shell: bash
        run: npm ci --ignore-scripts

      - name: Build
        run: npm run build

      - name: Lint
        run: npm run lint

      - name: Deploy
        if: endsWith(github.ref, 'main')
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: npx changeset publish --no-git-tag
