name: Release

on:
  push:
    branches:
      - main

concurrency: ${{ github.workflow }}-${{ github.ref }}

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Setup Node.js 18
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'npm'

      - name: Install Dependencies
        run: npm ci

      - name: Run lint
        run: npm run lint

        # Create release PR
      - if: github.ref != 'refs/heads/main'
        name: Create Release Pull Request
        uses: changesets/action@v1
        with:
          title: Release Version
          commit: Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

        # Publish to NPM
      - if: github.ref == 'refs/heads/main'
        name: Publish to NPM
        id: changesets
        uses: changesets/action@v1
        with:
          publish: npm run release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
